language: android
android:
  components:
    - build-tools-20.0.0
    - android-L
    - sys-img-x86-android-tv-l
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
script:
    sudo ./build.sh
