language: java
jdk:
  - oraclejdk8
before_install:

 # Download the SDK
 - wget http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz
 - tar -zxf android-sdk_r23.0.2-linux.tgz
 - export ANDROID_HOME=`pwd`/android-sdk-linux
 - NDK_VER=r9c
 - wget http://dl.google.com/android/ndk/android-ndk-$NDK_VER-linux-x86_64.tar.bz2
 - tar jxf android-ndk-$NDK_VER-linux-x86_64.tar.bz2
 - export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VER
 - export PATH=${PATH}:${ANDROID_NDK_HOME}
  # manually set sdk.dir variable, according to local paths
 - echo "sdk.dir=$ANDROID_HOME" > `pwd`/HLSPlayerSDK/local.properties
 - export NDK_PROJECT_PATH=`pwd`/HLSPlayerSDK/
 - sed -i "s@\${aapt}@${ANDROID_HOME}/tools/aapt@g" `pwd`/android-sdk-linux/tools/ant/build.xml
 - sed -i s#@NDK_BUILD_PATH@#`pwd`/android-ndk-$NDK_VER/ndk-build#g build.xml

 # Set the $PATH so all the tools like dx,aapt etc work
 - export PATH=$PATH:$ANDROID_HOME/tools
 - export PATH=$PATH:$ANDROID_HOME/platform-tools
 - export PATH=$PATH:$ANDROID_HOME/build-tools

 - sudo apt-get install expect

 - echo $PWD
 - source .license-accept-android.sh

 - license_accepted_android update sdk --force -u -t platform-tools

 # this command requires platform-tools installed first to work
 - android list sdk -a -u -e

 # actually get the packages we want
 - license_accepted_android update sdk --force -a -u -t tools,platform-tools,build-tools-21.1.1,android-10,extra-android-support

 # useful information to debug problems with previous steps
 - ls -lah ${ANDROID_HOME}
 - ls -lah ${ANDROID_HOME}/platforms
 - ls -lah ${ANDROID_HOME}/build-tools
 - ls -lah ${ANDROID_HOME}/tools
 - ls -lah ${ANDROID_HOME}/platform-tools


# Do this last because it takes so damn long, it's quicker to iterate on
 # refinements to prior section
 - sudo apt-get update
 - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch

script:
 - cd HLSPlayerSDK &&  ndk-build && ant release
